# Generated by Django 3.1.5 on 2021-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justapp', '0002_auto_20210120_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltimer',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
