# Generated by Django 3.1.5 on 2021-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justapp', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltimer',
            name='name',
            field=models.CharField(default='defalt', max_length=100),
            preserve_default=False,
        ),
    ]
