# Generated by Django 3.1.5 on 2021-01-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justapp', '0005_urltimer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urltimer',
            name='name',
        ),
    ]
